make_cmd_tests:
  normal_pipeline_args:
    args:
      alpha_high: '20000'
      alpha_k: '2500'
      chromosomes: null
      cnfile: __REQUIRED__
      estimate_ploidy: 'TRUE'
      genome_type: __REQUIRED__
      id: __REQUIRED__
      infile: __REQUIRED__
      map: __REQUIRED__
      max_copynumber: '8'
      max_depth: '200'
      max_iters: '5'
      myskew: '0'
      normal_estimate_method: map
      normal_param_nzero: __REQUIRED__
      num_clusters: '1'
      num_cores: '4'
      obj_outfile: __REQUIRED__
      outfile: __REQUIRED__
      outparam: __REQUIRED__
      ploidy: '2'
      pseudo_counts: 1e-300
      symmetric: 'TRUE'
      txn_exp_len: 1e9
      txn_z_strength: 1e9
      y_threshold: '20'
    chunk: 'null'
    output:
      cmd: Rscript component_seed/titan.R
      cmd_args:
      - __REQUIRED__
      - __REQUIRED__
      - __REQUIRED__
      - __REQUIRED__
      - '1'
      - '4'
      - '2'
      - __REQUIRED__
      - __REQUIRED__
      - '0'
      - 'TRUE'
      - __REQUIRED__
      - map
      - '5'
      - 1e-300
      - 1e9
      - 1e9
      - '2500'
      - '20000'
      - '8'
      - 'TRUE'
      - __REQUIRED__
      - __REQUIRED__
      - 'NULL'
      - '20'
      - '200'
